config/routes.rb
Edcentivize::Application.routes.draw do
  resources :users
  get '/leaders' => 'leaders#index'

  root :to => 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :operator, :level, :right, :wrong, :score

  def self.make_leaders(level)
    leaders = User.where(:level=>level).all.sort_by! {|u| u[:right]}.reverse
  end
  
  def find_user_rank
    leaders = User.make_leaders(self.level)
    leaders.collect! {|l| l.right}
    leaders.uniq!
    #once i have the set of unique scores, get the size of the set and 
    #find out what index number self is in. then return score and rank
    #i.e., "your score of 22 was third best"
    i = (leaders.find_index(self.right) + 1).ordinalize
    return i

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/leaders_controller.rb
class LeadersController < ApplicationController
  def index
    @level1 = User.make_leaders(1)
    @level2 = User.make_leaders(2)
    @level3 = User.make_leaders(3)
    @level4 = User.make_leaders(4)
    @level5 = User.make_leaders(5)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.new
  end
  
  def create
    @user = User.new
    @user.name = params[:name]
    @user.right = params[:right].to_i
    @user.wrong = params[:wrong].to_i
    @user.level = params[:level]
    if params[:operator] == "a"
      @user.operator = "+"
    elsif params[:operator] == "b"
      user.operator = "-"
    elsif params[:operator] == "c"
        user.operator = "*"
    elsif params[:operator] == "d"
        user.operator = "/"
    else
    end
    @user.save

    respond_to do |format|
       format.json {render :json => @user}#need to add @user.find_user_rank to json
    
    end

    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leaders_helper.rb
module LeadersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Edcentivize</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/leaders/index.html.erb
<h1>Leaders</h1>
<h2><%= link_to "Back", users_path %> </h2>

<table>
 <h2> Level 1 </h2>
  <th>Name</th>
  <th>Number Correct</th>
<% @level1.each do |leader| %>
  <tr>
    <td><%= leader.name %></td>
    <td><%= leader.right%></td>
  </tr>
  <% end %>
</table>

<table>
  <h2>Level 2</h2>
  <th>Name</th>
  <th>Number Correct</th>
<% @level2.each do |leader| %>
  <tr>
    <td><%= leader.name %></td>
    <td><%= leader.right%></td>
  </tr>
  <% end %>
</table>

<table>
 <h2> Level 3</h2>
  <th>Name</th>
  <th>Number Correct</th>
<% @level3.each do |leader| %>
  <tr>
    <td><%= leader.name %></td>
    <td><%= leader.right%></td>
  </tr>
  <% end %>
</table>

<table>
 <h2> Level 4</h2>
  <th>Name</th>
  <th>Number Correct</th>
<% @level4.each do |leader| %>
<tr>
  <td><%= leader.name %></td>
  <td><%= leader.right%></td>
</tr>
  <% end %>
</table>

<table>
  <h2>Level 5</h2>
  <th>Name</th>
  <th>Number Correct</th>
<% @level5.each do |leader| %>
<tr>
  <td><%= leader.name %></td>
  <td><%= leader.right%></td>
</tr>
  <% end %>
</table>

app/views/users/index.html.erb
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Calculations</title>
	<link rel="stylesheet" href="">
	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	<!-- <script type="text/javascript" src="/assets/clock.js" /> -->
</script>
</head>

<body>

	<div id='timer'></div>

	
	<div id="wrapper">
		
	<h1>Math Challenge!</h1>
		<div id="operator_levels">
			Choose Operator:
			<span id="operator"></span>
			<button class="operator" type="button" id="operator1" value="+">+</button>
			<button class="operator" type="button" id="operator2" value="-">-</button>
			<button class="operator" type="button" id="operator3" value="*">*</button>
			<button class="operator" type="button" id="operator4" value="/">/</button>
			
	
		</div>
		<div id="gear_levels">
			Choose Level:
			<span id="level"></span>
			<button class="gear" type="button" id="gear1" value="1">1</button>
			<button class="gear" type="button" id="gear2" value="2">2</button>
			<button class="gear" type="button" id="gear3" value="3">3</button>
			<button class="gear" type="button" id="gear4" value="4">4</button>
			<button class="gear" type="button" id="gear5" value="5">5</button>
		</div>
		<div id="start_line">
			<input type="text" value="Name or alias"></input>
			<button class="start" type="button" id="start1" value="">Start</button>
		</div>
		
		<div id="scoreboard">
			<span>Scores</span>
			<span>Right:</span><span id="total_right"></span>
			<span>Wrong:</span><span id="total_wrong"></span>
			<span>Final:</span><span id="rank_score"></span>
		</div>	
		
		<div>
			<table id="addition">
			<tr id="first">
				<td><span type="text">---</span> <span type="text">--</span> <span type="text">---</span> = <input type="text"></input></td>
				<td><span type="text">---</span> <span type="text">--</span> <span type="text">---</span> = <input type="text"></input></td>
				<td><span type="text">---</span> <span type="text">--</span> <span type="text">---</span> = <input type="text"></input></td>
				<td><span type="text">---</span> <span type="text">--</span> <span type="text">---</span> = <input type="text"></input></td>
				<td><span type="text">---</span> <span type="text">--</span> <span type="text">---</span> = <input type="text"></input></td>

			</tr>
			<tr id="second">
				<td><span type="text">---</span> <span type="text">--</span> <span type="text">---</span> = <input type="text"></input></td>
				<td><span type="text">---</span> <span type="text">--</span> <span type="text">---</span> = <input type="text"></input></td>
				<td><span type="text">---</span> <span type="text">--</span> <span type="text">---</span> = <input type="text"></input></td>
				<td><span type="text">---</span> <span type="text">--</span> <span type="text">---</span> = <input type="text"></input></td>
				<td><span type="text">---</span> <span type="text">--</span> <span type="text">---</span> = <input type="text"></input></td>

			</tr>
			<tr id="third">
				<td><span type="text">---</span> <span type="text">--</span> <span type="text">---</span> = <input type="text"></input></td>
				<td><span type="text">---</span> <span type="text">--</span> <span type="text">---</span> = <input type="text"></input></td>
				<td><span type="text">---</span> <span type="text">--</span> <span type="text">---</span> = <input type="text"></input></td>
				<td><span type="text">---</span> <span type="text">--</span> <span type="text">---</span> = <input type="text"></input></td>
				<td><span type="text">---</span> <span type="text">--</span> <span type="text">---</span> = <input type="text"></input></td>

			</tr>
			<tr id="fourth">
				<td><span type="text">---</span> <span type="text">--</span> <span type="text">---</span> = <input type="text"></input></td>
				<td><span type="text">---</span> <span type="text">--</span> <span type="text">---</span> = <input type="text"></input></td>
				<td><span type="text">---</span> <span type="text">--</span> <span type="text">---</span> = <input type="text"></input></td>
				<td><span type="text">---</span> <span type="text">--</span> <span type="text">---</span> = <input type="text"></input></td>
				<td><span type="text">---</span> <span type="text">--</span> <span type="text">---</span> = <input type="text"></input></td>

			</tr>
			<tr id="fifth">
				<td><span type="text">---</span> <span type="text">--</span> <span type="text">---</span> = <input type="text"></input></td>
				<td><span type="text">---</span> <span type="text">--</span> <span type="text">---</span> = <input type="text"></input></td>
				<td><span type="text">---</span> <span type="text">--</span> <span type="text">---</span> = <input type="text"></input></td>
				<td><span type="text">---</span> <span type="text">--</span> <span type="text">---</span> = <input type="text"></input></td>
				<td><span type="text">---</span> <span type="text">--</span> <span type="text">---</span> = <input type="text"></input></td>

			</tr>
		</table>



		</div>
		<h2><%= link_to "Leaders", leaders_path %> <h2>
		
			
	</div><!-- #wrapper -->
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="app/assets/javscripts/jquery-1.8.0.min.js"><\/script>')</script>
	
		
</body>
</html>